# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Export_Button.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from export_event_class import exportEventClass
from export_events import export_events_to_csv


class ExportEventPopup(object):
    def set_up_ui(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(407, 207)

        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 20, 351, 161))
        self.widget.setObjectName("widget")

        self.ExportFileName = QtWidgets.QTextEdit(self.widget)
        self.ExportFileName.setGeometry(QtCore.QRect(0, 0, 351, 31))
        self.ExportFileName.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ExportFileName.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ExportFileName.setLineWrapMode(QtWidgets.QTextEdit.FixedPixelWidth)
        self.ExportFileName.setTabStopWidth(54)
        self.ExportFileName.setObjectName("ExportFileName")
        export_file_name = self.ExportFileName.toPlainText()

        self.startDate = QtWidgets.QDateEdit(self.widget)
        self.startDate.setGeometry(QtCore.QRect(70, 40, 91, 31))
        self.startDate.setAutoFillBackground(False)
        self.startDate.setDateTime(QtCore.QDateTime.currentDateTime())
        #change format to yyyy-MM-dd
        self.startDate.setDisplayFormat("yyyy-MM-dd")
        self.startDate.setObjectName("startDate")
        #change startDate to string
        start_date = self.startDate.text()
        

        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 61, 30))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(180, 40, 61, 30))
        self.label_6.setObjectName("label_6")

        self.EndDate = QtWidgets.QDateEdit(self.widget)
        self.EndDate.setGeometry(QtCore.QRect(250, 40, 91, 31))
        self.EndDate.setAutoFillBackground(False)
        self.EndDate.setDateTime(QtCore.QDateTime.currentDateTime())
        self.EndDate.setDisplayFormat("yyyy-MM-dd")
        self.EndDate.setObjectName("EndDate")
        end_date = self.EndDate.text()


        #export this using event_class.py ignore other arguement
        
        export_event_data = exportEventClass(export_file_name, start_date, end_date)
      
        
        self.OkButton = QtWidgets.QPushButton(self.widget)
        self.OkButton.setGeometry(QtCore.QRect(60, 100, 93, 28))
        self.OkButton.setObjectName("OkButton")
        self.OkButton.clicked.connect(lambda: export_events_to_csv(export_event_data))


        self.CancelButton = QtWidgets.QPushButton(self.widget)
        self.CancelButton.setGeometry(QtCore.QRect(210, 100, 93, 28))
        self.CancelButton.setObjectName("CancelButton")
        self.CancelButton.clicked.connect(Dialog.close)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
       

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.startDate.setDisplayFormat(_translate("Dialog", "yyyy/mm/dd"))
        self.OkButton.setText(_translate("Dialog", "OK"))
        self.CancelButton.setText(_translate("Dialog", "CANCEL"))
        self.label_5.setText(_translate("Dialog", "start_date"))
        self.label_6.setText(_translate("Dialog", "end_date"))
        self.EndDate.setDisplayFormat(_translate("Dialog", "yyyy/mm/dd"))
        self.ExportFileName.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.ExportFileName.setPlaceholderText(_translate("Dialog", "Export File Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = ExportEventPopup()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
