# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# TestGUI.py
# GUI for the Personal Calendar Application
# Created by Roong, 20th October 2023

import sys
from create_event import CreateEventPopup
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

am_pm = ["AM", "PM"]
days_in_week = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"]
month_in_year = [
    'January', 'February', 'March', 'April', 
    'May', 'June', 'July', 'August', 
    'September', 'October', 'November', 'December'
]
current_day = 21

class Ui_Form(object): 
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(757, 654)
        self.widget = QtWidgets.QWidget(Form) # Create a widget for the ComboBox and TableWidgets
        self.widget.setEnabled(True)
        self.widget.setGeometry(QtCore.QRect(20, 60, 711, 551))
        self.widget.setObjectName("widget")

        self.comboBox = QtWidgets.QComboBox(self.widget)
        self.comboBox.setEnabled(True)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 111, 26))
        self.comboBox.setToolTipDuration(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.dateEdit = QtWidgets.QDateEdit(self.widget) # Create a DateEdit widget
        self.dateEdit.setEnabled(True)
        self.dateEdit.setGeometry(QtCore.QRect(290, 0, 131, 31))
        self.dateEdit.setMouseTracking(False)
        self.dateEdit.setTabletTracking(False)
        self.dateEdit.setAcceptDrops(False)
        self.dateEdit.setProperty("showGroupSeparator", False)
        self.dateEdit.setObjectName("dateEdit")

        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(420, 0, 51, 33))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 0, 51, 33))
        self.pushButton_4.setObjectName("pushButton_4")

        self.monthDisplay = QtWidgets.QTableWidget(self.widget)
        self.monthDisplay.setEnabled(True)
        self.monthDisplay.setGeometry(QtCore.QRect(10, 40, 701, 501))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.monthDisplay.setFont(font)
        self.monthDisplay.setAutoScrollMargin(16)
        self.monthDisplay.setRowCount(5)
        self.monthDisplay.setObjectName("Month Widget")
        self.monthDisplay.setColumnCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.monthDisplay.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthDisplay.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthDisplay.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthDisplay.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthDisplay.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.monthDisplay.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthDisplay.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthDisplay.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthDisplay.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthDisplay.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthDisplay.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.monthDisplay.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.monthDisplay.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.monthDisplay.setItem(0, 1, item)
        self.monthDisplay.horizontalHeader().setVisible(True)
        self.monthDisplay.horizontalHeader().setCascadingSectionResizes(True)
        self.monthDisplay.horizontalHeader().setDefaultSectionSize(100)
        self.monthDisplay.horizontalHeader().setMinimumSectionSize(0)
        self.monthDisplay.verticalHeader().setDefaultSectionSize(95)
        self.monthDisplay.verticalHeader().setMinimumSectionSize(0)

        self.weekDisplay = QtWidgets.QTableWidget(self.widget)
        self.weekDisplay.setGeometry(QtCore.QRect(10, 40, 701, 501))
        self.weekDisplay.setObjectName("Week Widget")
        self.weekDisplay.setColumnCount(7)
        self.weekDisplay.setRowCount(24)
        count = 0
        for i in am_pm:
            for j in range(1, 13, 1):
                item = QtWidgets.QTableWidgetItem()
                self.weekDisplay.setVerticalHeaderItem(count, item)
                count += 1
        for i, _ in enumerate(days_in_week):
            item = QtWidgets.QTableWidgetItem()
            self.weekDisplay.setHorizontalHeaderItem(i, item)

        self.dayDisplay = QtWidgets.QTableWidget(self.widget)
        self.dayDisplay.setGeometry(QtCore.QRect(10, 40, 701, 501))
        self.dayDisplay.setObjectName("Day Widget")
        self.dayDisplay.setColumnCount(1)
        self.dayDisplay.setRowCount(24)
        count = 0
        for i in am_pm:
            for j in range(1, 13, 1):
                item = QtWidgets.QTableWidgetItem()
                self.dayDisplay.setVerticalHeaderItem(count, item)
                count += 1
        item = QtWidgets.QTableWidgetItem()
        self.dayDisplay.setHorizontalHeaderItem(0, item)

        self.create_event_button = QtWidgets.QPushButton(Form)
        self.create_event_button.setGeometry(QtCore.QRect(180, 10, 81, 33))
        self.create_event_button.setObjectName("createEvent")
        self.create_event_button.clicked.connect(self.show_event_dialog)

        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 161, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")

        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 10, 100, 33))
        self.pushButton_2.setObjectName("pushButton_2")

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(390, 10, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(20, 40, 161, 301))
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setVisible(False)
        # Connect the currentIndexChanged signal of the ComboBox to the slot
        self.comboBox.currentIndexChanged.connect(self.onComboBoxIndexChanged)
        # Call the slot initially to set the initial state
        self.onComboBoxIndexChanged(0)  # assuming the initial index is 0
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def show_event_dialog(self):
        # Create an instance of the event creation dialog
        event_dialog = QDialog()
        ui = CreateEventPopup()                  
        ui.setupUi(event_dialog)
        # Show the dialog
        event_dialog.exec_()

    def onComboBoxIndexChanged(self, index):
        # Get the selected text from the ComboBox
        selected_text = self.comboBox.currentText()

        # Set the visibility of the TableWidgets based on the selected text
        if selected_text == "Month":
            self.monthDisplay.setVisible(True)
            self.weekDisplay.setVisible(False)
            self.dayDisplay.setVisible(False)
        elif selected_text == "Week":
            self.monthDisplay.setVisible(False)
            self.weekDisplay.setVisible(True)
            self.dayDisplay.setVisible(False)
        elif selected_text == "Day":
            self.monthDisplay.setVisible(False)
            self.weekDisplay.setVisible(False)
            self.dayDisplay.setVisible(True)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox.setItemText(0, _translate("Form", "Day"))
        self.comboBox.setItemText(1, _translate("Form", "Week"))
        self.comboBox.setItemText(2, _translate("Form", "Month"))
        self.pushButton_3.setText(_translate("Form", ">"))
        self.pushButton_4.setText(_translate("Form", "<"))
        for i, day in enumerate(days_in_week):
            item = self.monthDisplay.horizontalHeaderItem(i) # Add month headers
            item.setText(_translate("Form", day))
        __sortingEnabled = self.monthDisplay.isSortingEnabled()
        self.monthDisplay.setSortingEnabled(False)
        item = self.monthDisplay.item(0, 0)
        item.setText(_translate("Form", "1\n" "Sport Day"))
        self.monthDisplay.setSortingEnabled(__sortingEnabled)
        count = 0
        for i in am_pm:
            for j in range(1, 13, 1):
                item = self.weekDisplay.verticalHeaderItem(count)
                item.setText(_translate("Form", "{} {}".format(j, i)))
                count += 1
        for i, day in enumerate(days_in_week):
            item = self.weekDisplay.horizontalHeaderItem(i)
            item.setText(_translate("Form", "{} {}".format(day, current_day + i)))

        count = 0
        for i in am_pm:
            for j in range(1, 13, 1):
                item = self.dayDisplay.verticalHeaderItem(count)
                item.setText(_translate("Form", "{} {}".format(j, i)))
                count += 1
        self.create_event_button.setText(_translate("Form", "Create"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Search Event"))
        self.pushButton_2.setText(_translate("Form", "Export"))
        self.label.setText(_translate("Form", "19 October 2023"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
